services:
    backend:
        container_name: "Quantum-backend"
        hostname: 'backend'
        networks:
            - quantum-network
        restart: unless-stopped
        pull_policy: build
        depends_on:
            - postgres
            - elastic
        build:
            context: .
            dockerfile: deploy/Dockerfile
            target: production
        environment:
            DB_HOST: 'postgres'
        env_file:
            - .env
        ports:
            - "8000:8000"

    postgres:
        container_name: 'Quantum-postgres'
        hostname: 'postgres'
        networks:
            - quantum-network
        restart: unless-stopped
        image: postgres:alpine
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - quantum-postgres:/var/lib/postgresql/data

    elastic:
        container_name: "Quantum-elastic"
        hostname: 'elastic'
        networks:
            - quantum-network
        image: elasticsearch:8.15.3
        restart: unless-stopped

volumes:
  quantum-postgres:

networks:
  quantum-network:
    driver: bridge
